name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew bootJar --no-daemon
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 10m
        script: |
          # 기존 프로세스 종료
          sudo pkill -f java || true
          
          # 기존 JAR 파일 삭제
          rm -f *.jar
          
    - name: Upload JAR file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "build/libs/*.jar"
        target: "/home/ubuntu/"
        strip_components: 2
        
    - name: Start application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Spring Boot 백그라운드 실행
          nohup java -jar *.jar --server.port=8080 > app.log 2>&1 &
          
          # 잠시 대기 후 실행 확인
          sleep 15
          ps aux | grep java
          curl localhost:8080 || echo "Starting up..."
