name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd moya-BE
          git pull origin main
          
          # 기존 컨테이너 정지 및 제거
          docker stop moya-backend-container || true
          docker rm moya-backend-container || true
          docker rmi moya-be || true

          
          # 새 이미지 빌드 및 실행
          docker build -t moya-be .
          docker run -d -p 8080:8080 --name moya-backend-container moya-be
          
          # 컨테이너 상태 확인
          docker ps
          
          # 로그 확인 (Spring Boot 시작 확인)
          sleep 10
          docker logs moya-backend-container --tail 20
